### ISSUE TITLE
DotOverlay绘画类文档勘误

### ISSUE THREAD

**Issue by cheekahao** [TalkingData/inmap#10]
DotOverlay绘画类的文档中，发现下面几个问题：
1. 没有`style.normal.mergeCount`的解释；
2. tooltip.offsets在示例三中是一个对象，但是在文档中的解释为Number类型
3. style.normal.globalCompositeOperation文档中没有解释
4. legend.title文档中没有解释

**Comment by fengluhome** [comment]
已修复
