### ISSUE TITLE
官网文档点击左侧菜单都会回到intrduce

### ISSUE THREAD

**Issue by momominchen** [TalkingData/inmap#12]
url：http://inmap.talkingdata.com/#/docs/introduce
如题。

**Comment by chenli8** [comment]
@momominchen 请问你用的什么浏览器？浏览器版本是什么?我这边复现不了，能否在详细点

**Comment by momominchen** [comment]
系统：win10
浏览器：chrome 63.0
![image](https://user-images.githubusercontent.com/7303678/34810746-37a6254e-f6d8-11e7-87be-3a426bc88b85.png)

**Comment by momominchen** [comment]
系统：win10
浏览器：chrome 63.0
![image](https://user-images.githubusercontent.com/7303678/34811051-da46b22c-f6d9-11e7-931d-4654eff9e5d3.png)

![inmap](https://user-images.githubusercontent.com/7303678/34811036-bf6fe34c-f6d9-11e7-85af-b029fffc22cb.gif)

**Comment by fengluhome** [comment]
@momominchen  还是无法复现这个问题，是不是你的系统环境问题造成的？

**Comment by momominchen** [comment]
目前只发现这个页面存在问题，iview就没事。。不知道什么情况

**Comment by fengluhome** [comment]
进入QQ群 618308202 交流吧 GitHub交流太困难了

**Comment by fengluhome** [comment]
已解决
