### ISSUE TITLE
鼠标指针和提示的位置

### ISSUE THREAD

**Issue by zboMa** [TalkingData/inmap#14]
![image](https://user-images.githubusercontent.com/26337768/37439059-05fd4ef2-2831-11e8-89de-2250365926f8.png)
这个地方在鼠标放上去的时候，是一个小手，会把那个数字遮住，也就是说指针遮住了一部分提示内容。
http://inmap.talkingdata.com/#/docs/introduce 这个页面最后面的示例里。

**Comment by fengluhome** [comment]
可以配置tooltip的偏移，来改善悬浮窗的显示效果：
 tooltip: {
         show: false,
         customClass: 'inmap-tooltip-black', //是否自定义样式
         offsets: {
             top: 0, //上偏移
             left: 0 //左偏移
         }

     }

**Comment by zboMa** [comment]
好的，谢谢
