### ISSUE TITLE
在安装指引的时候，直接给出一个百度地图的ak是不是不大好

### ISSUE THREAD

**Issue by misakamaiyako** [TalkingData/inmap#2]
百度地图的ak除了申请使用地图，还有统计、限制平台等功能，我觉得应当引导开发者去自己申请一个，而不是给出一个公共的ak。

**Comment by fengluhome** [comment]
当时决定放百度地图的ak是出于让方便开发者快速构建出demo的目的，是不建议开发者在实际项目中使用公共的ak，文档是有建议用户去申请百度的ak，[请查看](http://inmap.talkingdata.com/#/docs/guide/course)
