### ISSUE TITLE
FlashDotOverlay onState回调不起作用

### ISSUE THREAD

**Issue by cheekahao** [TalkingData/inmap#20]
FlashDotOverlay onState回调不起作用

**Comment by fengluhome** [comment]
FlashDotOverlay对象并没有提供onState的事件订阅，主要原因有：
1.onState 回调状态，0：worker计算前、1：worker计算后、2：canvas绘画前、3：canvas绘画后；而flashDotOverlay比较特殊，数据量小，并没有采用worker转换，而且需要不断的动画重绘，如果触发onState就会不断触发 2和3绘画 ，所以并没有该回调。
