### ISSUE TITLE
PointOverlay-BigData演示页面很卡

### ISSUE THREAD

**Issue by vip16** [TalkingData/inmap#22]
官网说效果最好的传入数据量为1W到10W，为何该演示页面8万多的数据，就很卡？是否显示大数据场景仅为在某一个缩放等级下展示大数据，而不适合切换缩放级别的场景？

**Comment by fengluhome** [comment]
PointOverlay-BigData采用的批量绘制，我们的机子十几万的都没有问题的，可能这么的数据量，需要的内存空间大一些，请问一下您的机器配置多少？

**Comment by vip16** [comment]
我的是16G内存，i7的处理器。绘制的时候不卡，但是绘制完成，对地图进行缩放或者拖动的时候就很卡

**Comment by vip16** [comment]
那这种连续缩放的，你们会怎么处理呢？

**Comment by fengluhome** [comment]
最终目的尽可能减少没必要的绘画，这个还有优化空间， 谢谢你的反馈。

**Comment by vip16** [comment]
好的，谢谢
