### ISSUE TITLE
PolygonEditorOverlay报错overlay.addEventListener is not a function

### ISSUE THREAD

**Issue by cheekahao** [TalkingData/inmap#23]
let overlay = new inMap.PolygonEditorOverlay({
    style: {
        strokeColor: 'rgba(24,144,255,1)',
        fillColor: 'rgba(24,144,255,0.4)',
        strokeWeight: 2,
        strokeOpacity: 1,
        enableEditing: true
    },
    data: data
});
overlay.addEventListener('lineupdate', e =>console.log(e));
inmap.add(overlay);

**Comment by fengluhome** [comment]
已修复
