### ISSUE TITLE
IE11下JS报错的问题

### ISSUE THREAD

**Issue by meepo3927** [TalkingData/inmap#24]
系统：windows 10 专业版64位
浏览器：IE11
URL：http://localhost:8088/examples/MoveLineOverlay.html

发现两处报错：
1. Array.prototype.findIndex 未定义
2. 代码：
{
        key: 'compileTooltipTemplate',
        value: function compileTooltipTemplate(formatter) {
            formatter = '`' + formatter.replace(/\{/g, '${overItem.') + '`';
            this.tooltipTemplate = new Function('overItem', 'return ' + formatter); // 此行运行时报错
}

**Comment by meepo3927** [comment]
1. Array.prototype.findIndex的问题，可以Polyfill解决。

2. 使用了ES6的语法，IE11不支持，运行时报错。改为正则替换可解决。

**Comment by fengluhome** [comment]
太感谢你了 😆
