### ISSUE TITLE
[Bug Report]多图层时tooltip无法正常显示问题

### ISSUE THREAD

**Issue by kkltmoyu** [TalkingData/inmap#35]
出现环境：Win7 x64，chrom 版本 68.0.3440.106（正式版本） （32 位）
问题复现链接：http://smartdata.b0.upaiyun.com/inmap/PointOverlay02.html
问题描述：地图上绘制的黄色小方块，tooltip无法正常显示
问题原因推测：由于在地图上移动鼠标回触发各个overlay的_tMousemove方法，各个图层会调用getTarget方法从自身的workerData中查找当前event的pixel是否存在点，当点出现在第一个图层时，会调用tooltip.render将tooltip的dom的display设置为true，但第二个图层在getTarget是返回的是null，故又会将tooltip的dom的display设置为false，故导致tooltip无法正常显示。
解决方案：目前只想到一个解决方案是在tmousemove方法中加入一个判断，即在event.geometry.pixel不变的情况下，如果gettarget方法命中一个非null的图层，在鼠标不动的情况下，不去再次调用settooltip方法。但是此方法可能无法适用于多图层点重合的情况

**Comment by fengluhome** [comment]
哈哈 感谢你的提的问题和修改建议。  本质问题是多个图层共享了同一个ToolTip实例， 如果他们使用自己的ToolTip对象，这样就不会有这种争抢资源的怪异问题。
