### ISSUE TITLE
如何关闭文字避让

### ISSUE THREAD

**Issue by kxw1059** [TalkingData/inmap#36]

**Comment by fengluhome** [comment]
lable 设置为false

**Comment by kxw1059** [comment]
在地图的所有缩放等级都显示文字怎么设置啊？

**Comment by kxw1059** [comment]
![image](https://user-images.githubusercontent.com/6478020/45737825-676dec80-bc21-11e8-9ab0-924745ca7b67.png)
![image](https://user-images.githubusercontent.com/6478020/45737832-6f2d9100-bc21-11e8-9fe2-27831fbe731b.png)

**Comment by fengluhome** [comment]
没有这种配置

**Comment by fengluhome** [comment]
如果都显示文字 效果会很糟糕

**Comment by kxw1059** [comment]
好的 谢谢了

**Comment by xianshenglu** [comment]
@fengluhome 可以暴露给用户，就算丑，用户也可以选择关掉啊；但是不暴露给用户，就很不方便啊；就像，你跟领导说，这样丑，领导说，你让我看看吗，= = 结果，根本看不了，，，
