### ISSUE TITLE
为何百度地图导出的json无法使用？

### ISSUE THREAD

**Issue by yuanhuanwebfront** [TalkingData/inmap#48]
使用方法如下： 
`{
     skin: {
           "featureType": "land",
           "elementType": "all",
           "stylers": {
                  "color": "#05131fff"
             }  
     }
}`

这样设置无法生效

**Comment by fengluhome** [comment]
传入的参数有些问题，向下面那样用数组包裹起来
`  skin: [{
            "featureType": "land",
            "elementType": "all",
            "stylers": {
                "color": "#05131fff"
            }
        }],`

**Comment by yuanhuanwebfront** [comment]
> 传入的参数有些问题，向下面那样用数组包裹起来
> ` skin: [{ "featureType": "land", "elementType": "all", "stylers": { "color": "#05131fff" } }],`
谢谢啦。 我还以为是Object格式的
