### ISSUE TITLE
Always show tooltip?

### ISSUE THREAD

**Issue by sunqingyao** [TalkingData/inmap#7]
Currently, users have to hover on a data point to see the tooltip, which is inconvenient or even impossible on mobile devices.

I think it would be great if I can make tooltips always showing, or alternatively, able to add a fixed label on the map.

**Comment by icarusion** [comment]
Thanks for your comment. It is necessary to support mobile.

**Comment by icarusion** [comment]
@fengluhome

**Comment by fengluhome** [comment]
👌
