### ISSUE TITLE
如何动态修改地图的 zoom ？

### ISSUE THREAD

**Issue by fuyi501** [TalkingData/inmap#82]
我想通过某些点击事件来改变地图的缩放大小，如何动态设置 zoom 的值？

**Comment by fuyi501** [comment]
获取 bmap 实例，使用 bmap 实例可以来改变 zoom

**Comment by poetL** [comment]
请问 bmap 是  inmap._map么

**Comment by poetL** [comment]
> 请问 bmap 是 inmap._map么

inmap.getMap()
