### ISSUE TITLE
请问PolygonOverlay 方法中的设置选中数据是不是写错了

### ISSUE THREAD

**Issue by tmactara** [TalkingData/inmap#83]
http://inmap.talkingdata.com/#/docs/v2/PolygonOverlay 这里的文档说明中 PolygonOverlay 方法中的设置选中数据是不是写错了？

**Comment by fengluhome** [comment]
没有的亲。

**Comment by tmactara** [comment]
setOptionStyle(data:Array< Polygon\|MultiPlygon>) | none | 设置选中数据
-- | -- | --


我看是这样的正确的写法应该是 setSelectedList呀

**Comment by fengluhome** [comment]
下面的示例， 参数都类似：
` 
let data = [{"name":"线路一","geometry":{"type":"LineString","coordinates":[[115.661434,38.61384],[116.395645,39.929986]]},"count":1},{"name":"线路二","geometry":{"type":"LineString","coordinates":[[117.210813,39.14393],[116.395645,39.929986]]},"count":2},{"name":"线路三","geometry":{"type":"LineString","coordinates":[[118.527663,36.09929],[116.395645,39.929986]]},"count":3},{"name":"线路四","geometry":{"type":"LineString","coordinates":[[112.515496,37.866566],[116.395645,39.929986]]},"count":4},{"name":"线路五","geometry":{"type":"LineString","coordinates":[[122.753592,41.6216],[116.395645,39.929986]]},"count":5},{"name":"线路六","geometry":{"type":"LineString","coordinates":[[113.486804,34.157184],[116.395645,39.929986]]},"count":6},{"name":"线路七","geometry":{"type":"LineString","coordinates":[[119.368489,33.013797],[116.395645,39.929986]]},"count":2},{"name":"线路八","geometry":{"type":"LineString","coordinates":[[121.487899,31.249162],[116.395645,39.929986]]},"count":1},{"name":"线路九","geometry":{"type":"LineString","coordinates":[[113.394818,23.408004],[116.395645,39.929986]]},"count":5}]
var inmap = new inMap.Map({
    id: 'allmap',
    skin: "Blueness",
    center: [109.403119, 38.028658],
    zoom: {
        value: 6,
        show: true,
        max: 18,
        min: 5
    },
});

var overlay = new inMap.LineStringOverlay({
    tooltip: {
        show: true,
        formatter: '{name}',
    },
    style: {
        normal: {
            borderColor: 'rgba(200, 200, 50, 1)',
            borderWidth: 1,
            shadowColor: 'rgba(255, 250, 50, 1)',
            shadowBlur: 20,
            lineOrCurve: 'line', //curve or line
        },
        mouseOver: {
            borderColor: 'rgba(255, 255, 255, 1)'
        },
        selected: {
            borderColor: 'rgba(184,0,0,1)',
        },
        splitList: [{
                start: 0,
                end: 1,
                borderWidth: 1,
                borderColor: 'rgba(156,200,249,1)'
            },
            {
                start: 1,
                end: 2,
                borderWidth: 2,
                borderColor: 'rgba(93,158,247,1)'
            },
            {
                start: 3,
                end: 4,
                borderWidth: 3,
                borderColor: 'rgba(134,207,55,1)'
            },
            {
                start: 5,
                borderWidth: 4,
                borderColor: "rgba(252,198,10,1)"
            }
        ]
    },
    data: data,
    selected:[data[data.length-1]], //设置选中最后一条数据
});
inmap.add(overlay);
`

**Comment by fengluhome** [comment]
`
 
let data = [{"name":"线路一","geometry":{"type":"LineString","coordinates":[[115.661434,38.61384],[116.395645,39.929986]]},"count":1},{"name":"线路二","geometry":{"type":"LineString","coordinates":[[117.210813,39.14393],[116.395645,39.929986]]},"count":2},{"name":"线路三","geometry":{"type":"LineString","coordinates":[[118.527663,36.09929],[116.395645,39.929986]]},"count":3},{"name":"线路四","geometry":{"type":"LineString","coordinates":[[112.515496,37.866566],[116.395645,39.929986]]},"count":4},{"name":"线路五","geometry":{"type":"LineString","coordinates":[[122.753592,41.6216],[116.395645,39.929986]]},"count":5},{"name":"线路六","geometry":{"type":"LineString","coordinates":[[113.486804,34.157184],[116.395645,39.929986]]},"count":6},{"name":"线路七","geometry":{"type":"LineString","coordinates":[[119.368489,33.013797],[116.395645,39.929986]]},"count":2},{"name":"线路八","geometry":{"type":"LineString","coordinates":[[121.487899,31.249162],[116.395645,39.929986]]},"count":1},{"name":"线路九","geometry":{"type":"LineString","coordinates":[[113.394818,23.408004],[116.395645,39.929986]]},"count":5}]
var inmap = new inMap.Map({
    id: 'allmap',
    skin: "Blueness",
    center: [109.403119, 38.028658],
    zoom: {
        value: 6,
        show: true,
        max: 18,
        min: 5
    },
});

var overlay = new inMap.LineStringOverlay({
    tooltip: {
        show: true,
        formatter: '{name}',
    },
    style: {
        normal: {
            borderColor: 'rgba(200, 200, 50, 1)',
            borderWidth: 1,
            shadowColor: 'rgba(255, 250, 50, 1)',
            shadowBlur: 20,
            lineOrCurve: 'line', //curve or line
        },
        mouseOver: {
            borderColor: 'rgba(255, 255, 255, 1)'
        },
        selected: {
            borderColor: 'rgba(184,0,0,1)',
        },
        splitList: [{
                start: 0,
                end: 1,
                borderWidth: 1,
                borderColor: 'rgba(156,200,249,1)'
            },
            {
                start: 1,
                end: 2,
                borderWidth: 2,
                borderColor: 'rgba(93,158,247,1)'
            },
            {
                start: 3,
                end: 4,
                borderWidth: 3,
                borderColor: 'rgba(134,207,55,1)'
            },
            {
                start: 5,
                borderWidth: 4,
                borderColor: "rgba(252,198,10,1)"
            }
        ]
    },
    data: data,
    selected:[data[data.length-1]], //设置选中最后一条数据
});
inmap.add(overlay);

`

**Comment by tmactara** [comment]
在 文档-> 围栏-> PolygonOverlay 方法中

**Comment by fengluhome** [comment]
也可以通过setSelectedList 函数的途径 去设置选中

**Comment by tmactara** [comment]
![微信截图_20190612150043](https://user-images.githubusercontent.com/48339426/59330738-db5aa280-8d24-11e9-8d71-2795609b827b.png)
谢谢  这里确实写错了

**Comment by fengluhome** [comment]
感谢反馈
